---
swagger: "2.0"
info:
  version: "v1"
  title: "Swagger spec for our REST API"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
paths:
  /books:
    get:
      summary: "Get books"
      description: ""
      operationId: "getBooks"
      parameters: []
      responses:
        200:
          description: "Books retrieved"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Book"
    post:
      summary: "Adds book"
      description: ""
      operationId: "addBook"
      parameters: []
      responses:
        200:
          description: "Book added"
definitions:
  Book:
    type: "object"
    properties:
      isbn:
        type: "string"
      title:
        type: "string"
      authors:
        type: "array"
        items:
          type: "string"
