---
swagger: "2.0"
info:
  version: "v1"
  title: "Swagger spec for our REST API"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
tags:
- name: "books"
paths:
  /books:
    get:
      tags:
      - "books"
      summary: "Get books"
      description: ""
      operationId: "getBooks"
      parameters:
      - name: "filter"
        in: "query"
        required: false
        type: "string"
      responses:
        200:
          description: "Books retrieved"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Book"
    post:
      tags:
      - "books"
      summary: "Adds book"
      description: ""
      operationId: "addBook"
      parameters:
      - in: "body"
        name: "body"
        required: false
        schema:
          $ref: "#/definitions/Book"
      responses:
        200:
          description: "Book added"
definitions:
  Book:
    type: "object"
    properties:
      isbn:
        type: "string"
      title:
        type: "string"
      authors:
        type: "array"
        items:
          type: "string"
