/**
 * NOTE: This class is auto generated by the swagger code generator program (2.2.3).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.example.endpoint;

import com.example.model.Actor;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2017-10-15T23:45:57.158+02:00")

@Api(value = "actors", description = "the actors API")
public interface ActorsApi {

    @ApiOperation(value = "", notes = "Return a list of actors", response = Actor.class, responseContainer = "List", tags={ "Actors", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Successful response", response = Actor.class, responseContainer = "List") })
    
    @RequestMapping(value = "/actors",
        method = RequestMethod.GET)
    ResponseEntity<List<Actor>> getActors();

}
